config/routes.rb
Rails.application.routes.draw do
  get 'categories/news'
  get 'categories/programming'
  get 'categories/education'
  get 'categories/sports'
  get 'categories/humor'

  root "posts#index"
  resources :users

  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  resources :sessions, only: [:create]
  resources :posts do
    member do
      post 'vote'
    end

    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  resources :comments, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :comment_votes, dependent: :destroy
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment

  # Make sure a User can vote (up or down) on a Comment only once
  validates :user_id, uniqueness: { scope: :comment_id }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, uniqueness: true
  has_many :comments, dependent: :destroy
  has_many :post_votes, dependent: :destroy

  # required by pretty URL
  def to_param
    slug
  end
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # Make sure a User can vote (up or down) on a Post only once
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true
  validates :time_zone, inclusion: { in: ActiveSupport::TimeZone.zones_map.keys }
  has_many :posts
  has_many :comments

  # required by pretty URL
  def to_param
    username
  end

  def username=(value)
    value = value.strip.downcase
    write_attribute(:username, value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_post
  around_filter :user_time_zone, if: :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_post
    @current_post ||= Post.find_by_slug(session[:post_id]) if session[:post_id]
  end

  def sign_in(user)
    session[:user_id] = user.id if user.present?
  end

  def sign_out
    session[:user_id] = nil
  end

  def user_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def news
    query("news")
  end

  def programming
    query("programming")
  end

  def education
    query("education")
  end

  def sports
    query("sports")
  end

  def humor
    query("humor")
  end

  private
  # Utility method used by all the actions in this controller
  def query(column)
    @posts = Post.where("#{column} = 't'")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    # Create a new Comment
    @comment = current_post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      # If save was successful, then redirect to the Post#show view, using
      # the post_id stored previously in the session variable
      redirect_to post_path(session[:post_id])
    else
      render "new"
    end
  end

  def index
  end

  def vote
    logger.debug("NGUYEN, params: #{params.inspect}")
    @comment = Comment.find(params[:id])
    if @comment
      logger.debug("NGUYEN, found comment: #{@comment.inspect}")
      vote = @comment.comment_votes.build(user_id: @comment.user_id)
      if vote.save
        logger.debug("NGUYEN, saved vote: #{vote.inspect}")
        @comment.vote_count += (params[:vote] == "true" ? 1 : -1)
        @comment.save
      end
    else
      logger.debug("NGUYEN, comment NOT FOUND")
    end
    redirect_to(posts_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    # Create a new Post
    @post = current_user.posts.build(post_params)
    # Make sure to generate a slug as well
    @post.slug = @post.title.downcase.gsub(" ", "-")
    if @post.save
      # If save was sucessful, then redirect to the Post#index view
      flash[:success] = "Your post was created!"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def index
    @posts = Post.all
  end

  def show
    # Save the id/slug of the Post, so the Post can be retrieved later from
    # inside a Comment
    session[:post_id] = params[:id]
    # Find by slug and not by id
    @post = Post.find_by_slug(params[:id])
  end

  def destroy
  end

  def vote
    # Pretty URL enforced; so must look up Post by slug instead of by id
    @post = Post.find_by_slug(params[:id])
    if @post
      # Attempt to create a new vote that's linked to the current post and
      # current user
      vote = @post.post_votes.build(user_id: current_user.id)
      if vote.save
        # Increase or decreate the vote count accordingly. Note the param value
        # is passed as a string ("true" or "false") and not as a bool
        @post.vote_count += (params[:vote] == "true" ? 1 : -1)
        @post.save
      end
    end
    redirect_to(posts_path)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description,
     :news, :programming, :education, :sports, :humor)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid username/password"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      # redirect to username instead of id, due to pretty URL
      redirect_to user_path(@user.username)
    else
      render "new"
    end
  end

  def index
    @users = User.all
  end

  def show
    # Find by username instead of id, due to pretty URL
    @user = User.find_by_username(params[:id])
    if @user
      @posts = @user.posts
      @comments = Comment.where(user_id: "#{@user.id}")
    else
      render file: 'public/500.html'
    end
  end

  def edit
    @user = User.find_by_username(params[:id])
  end

  def update
    @user = User.find_by_username(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def full_url link
    if link.include?("http://")
      link
    else
      link = "http://" + link
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/education.html.erb
<%= render 'shared/category', category: "Education" %>

app/views/categories/humor.html.erb
<%= render 'shared/category', category: "Humor" %>

app/views/categories/news.html.erb
<%= render 'shared/category', category: "News" %>

app/views/categories/programming.html.erb
<%= render 'shared/category', category: "Programming" %>

app/views/categories/sports.html.erb
<%= render 'shared/category', category: "Sports" %>

app/views/comments/new.html.erb
<%= render 'shared/badge' %>

<%= form_for @comment do |f| %>
  <div style="margin:0; padding: 0; display: inline"></div>
  <div class="control-group">
    <%= f.label "Leave a comment" %>
    <%= f.body id="comment_body" class="span4" rows="3" %>
  </div>
  <%= f.submit "Create comment" %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <li><%= link_to "Postit!", root_path, class: "brand" %></li>
        </ul>

        <div class="btn-group nav_item">
          <a class="btn btn-small dropdown-toggle" href="#" data-toggle="dropdown">
            Categories
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu">
            <% categories = %w(news programming education sports humor) %>
            <% categories.each do |category| %>
              <li><%= link_to category.capitalize, "/categories/#{category}" %></li>
            <% end %>
          </ul>
        </div>
        <% if current_user %>
          <div class="nav_item">
            <%= link_to "New Post", new_post_path, class: "btn btn-success btn-small" %>
          </div>

          <div class="btn-group nav_item">
            <%= link_to "", class: "btn btn-small dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= current_user.username %>
              <span class="caret"></span>
            <% end %>

            <ul class="dropdown-menu">
              <li><%= link_to "edit profile", edit_user_path(current_user) %></li>
              <li><%= link_to "view profile", user_path(current_user) %></li>
              <li><%= link_to "logout", "/logout" %></li>
            </ul>
          </div>
        <% else %>
          <div class="nav_item">
            <%= link_to "Register", new_user_path, class: "btn btn-success btn-small" %>
          </div>

          <div class="nav_item">
            <%= link_to "Log in", login_path, class: "btn btn-small" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="main" role="main">
      <div class="container">
        <%= notice %>
        <%= alert %>
        <%= yield %>
        <footer></footer>
      </div>
    </div>
  </body>
</html>

app/views/posts/_welcome.html.erb
<div class="alert alert-block">
  <button type="button" class="close" data-dismiss="alert"></button>
  <h3>Welcome!</h3>
  "This is the application we build during the 2nd course for "
  <%= link_to "Tealeaf Academy", "http://www.gotealeaf.com" %>
  ". This is a Reddit-like application, with all features built from scratch
  without relying on any external libraries or gems."
</div>

app/views/posts/index.html.erb
<%= render 'shared/category' %>

app/views/posts/new.html.erb
<p>Create a new post</p>
<hr></hr>
<p></p>
<div>
  <%= form_for @post do |f| %>
    <div>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :url %><br/>
      <%= f.text_field :url %>
    </div>
    <div>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :categories %><br/>
      <%= f.check_box :news %>
      <%= f.label :news %>
      <%= f.check_box :programming %>
      <%= f.label :programming %>
      <%= f.check_box :education %>
      <%= f.label :education %>
      <%= f.check_box :sports %>
      <%= f.label :sports %>
      <%= f.check_box :humor %>
      <%= f.label :humor %>
    </div>
  <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="main" role="main">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="alert alert-success">
          <a class="close" data-dismiss="alert">x</a>
          <div id="flash_notice">Your comment was added.</div>
        </div>

        <p class="pull-right">
          [<%= link_to "edit this post", edit_post_path %>]
        </p>

        <%= render 'shared/badge', post: @post %>

        <p class="lead"><%= @post.title %></p>
        <hr></hr>
        <p></p>

        <p><%= @post.description %></p>
        <hr></hr>

        <%-# The Comment entity for the form is empty, standalone, and -%>
        <%-# unconnected to the Post entity. Only when a new Comment is -%>
        <%-# entered and submitted will it be linked to the Post entity via -%>
        <%-# CommentsController#create(). Otherwise linking the Comment early -%>
        <%-# would create an additional empty (mostly nil fields) Comment in -%>
        <%-# the array of Comments linked to Post, causing error and headache -%>
        <%= form_for Comment.new do |f| %>
          <div style="margin:0; padding: 0; display: inline"></div>
          <div class="control-group">
            <%= f.label "Leave a comment" %><br/>
            <%= f.text_area :body, id: "comment_body", class: "span4", rows: "3" %>
          </div>
          <%= f.submit "Create comment" %>
        <% end %>

        <h5>Comments:</h5>

        <% @post.comments.each do |c| %>
          <%= render 'shared/comment', comment: c %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_badge.html.erb
<p>
  <% categories = %w(news programming education sports humor) %>
  <% categories.each do |category| %>
    <% if eval("post.#{category}") %>
      <span class="badge">
        <%= link_to category.capitalize, "/categories/#{category}" %>
      </span>
    <% end %>
  <% end %>
</p>

app/views/shared/_category.html.erb
<div id="main">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p class="lead">
          <% if defined?(category) %>
            <%= link_to "All Posts", posts_path %>
            <%= ">> #{category}" %>
          <% else %>
            <%= "All Posts" %>
          <% end %>
        </p>
        <hr></hr>

        <p></p>
        <% @posts.each do |p| %>
          <%= render 'shared/post', post: p %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<div class="row">
  <%= render 'shared/comment_vote', comment: comment %>

  <div class="span8 well">
    <em>"<%= comment.body %>"</em>
    <br><br/>
    <span class="quiet">by</span>
    <%-# look for User from within a Comment -%>
    <% user = User.find(comment.user_id) %>
    <%= link_to user.username, user_path(user) %>
    <small><%= "at #{comment.created_at}" %></small>
  </div>
</div>

app/views/shared/_post.html.erb
<div class="row">
  <%= render 'shared/post_vote', post: post %>

  <div class="span8 well">
    <%= render 'shared/badge', post: post %>

    <h4><%= link_to post.title, full_url(post.url) %></h4>
    <p><%= post.description %></p>

    <p>
      <span class="quiet">posted by</span>
      <%-# look for User from within a Post -%>
      <% user = User.find(post.user_id) %>
      <%= link_to user.username, user_path(user) %>
      <small>at <%= post.created_at %></small>
    </p>

    <small>
      <span>
        <%= link_to "#{post.comments.count} comments", post_path(post) %>
      </span>
    </small>
  </div>
</div>

app/views/shared/_post_vote.html.erb
<div class="span0 well text-center">
  <%= link_to("#{vote_post_path(post.slug)}?vote=true", rel: "nofollow", remote: true, method: :post) do %>
    <span class="glyphicon glyphicon-arrow-up"></span>
  <% end %>
  </br>
  <span><%= "#{post.vote_count} votes" %></span>
  </br>
  <%= link_to("#{vote_post_path(post.slug)}?vote=false", rel: "nofollow", remote: true, method: :post) do %>
    <span class="glyphicon glyphicon-arrow-down"></span>
  <% end %>
</div>

app/views/shared/_pvote.html.erb
<div class="span0 well text-center">
  <%= link_to("#{post_path(post.slug)}/vote?vote=true", rel: "nofollow", remote: true, method: :post) do %>
    <span class="glyphicon glyphicon-arrow-up"></span>
  <% end %>
  </br>
  <span><%= "#{post.vote_count} votes" %></span>
  </br>
  <%= link_to("#{post_path(post.slug)}/vote?vote=false", rel: "nofollow", remote: true, method: :post) do %>
    <span class="glyphicon glyphicon-arrow-down"></span>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class="row">
  <div class="span12">
    <p class="lead"><%= title %></p>
    <hr></hr>
    <p></p>
    <div class="well">
      <%= form_for(@user, html: {id: "new_user", class: "new_user"}) do |f| %>
        <div style="margin:0;padding:0;display:inline"></div>
        <div class="control-group">
          <%= f.label :username %>
          <%= f.text_field :username %>
        </div>
        <div class="control-group">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="control-group">
          <%= f.label :time_zone %>
          <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
        </div>
        <div class="control-group">
          <%= f.submit button, html: {class: "btn btn-success"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: 'shared/user', locals: {title: "Edit Profile", button: "Update Profile"} %>

app/views/users/new.html.erb
<%= render partial: 'shared/user', locals: {title: "Register", button: "Register"} %>

app/views/users/show.html.erb
<% username = @user.username %>
<p class="lead">Profile: <%= username %></p>
<hr></hr>
<p></p>
<div class="well">
  <dl class="dl-horizontal">
    <dt>Username: </dt>
    <dd><%= username %></dd>
    <dt>Timezone: </dt>
    <dd><%= @user.time_zone %></dd>
  </dl>
</div>

<h5><%= username %>'s Activity</h5>
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Posts (#{@posts.count})", user_path(@user) %>
  </li>
  <li class="">
    <%= link_to "Comments (#{@comments.count})", "#{user_path(@user)}?tab=comments" %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @posts.each do |p| %>
    <%= render 'shared/post', post: p %>
  <% end %>
<% else %>
  <% @comments.each do |c| %>
    <%= render 'shared/comment', comment: c %>
  <% end %>
<% end %>